### ISSUE TITLE
Getting an error with lineAndCharacter

### ISSUE THREAD

**Issue by micky2be** [tbasse/tslint-formatter-eslint-style#1]
``` js
TypeError: lineAndCharacter.line is not a function
    at /Users/me/.nvm/versions/node/v5.9.0/lib/node_modules/tslint-path-formatter/index.js:87:28
```

Using tslint 3.15.1

**Comment by tbasse** [comment]
@micky2be, from the path in your error message it looks like your issue is with [tslint-path-formatter](https://github.com/Bartvds/tslint-path-formatter) and not with my formatter.

Tested mine with `tslint 3.15.1` and it seems to work fine.

**Comment by micky2be** [comment]
Wait, how are we suppose to use your formatter.
The name in the code stand for **tslint-path-formatter** so I assumed I should run `tslint 'src/**/**.ts?(x)' -t tslint-path-formatter`

But if I run `tslint 'src/**/**.ts?(x)' -t tslint-formatter-eslint-style` I get the error `formatter 'tslint-formatter-eslint-style' not found`.
